language: php

php:
  - 5.4
  - 5.5
  - hhvm

notifications:
  email: false
  slack:
    secure: Gljn/4LaCCu+nUZjroQqEkE1dr9mdbP4Ff7zeG0eEY5m1Lx7dBLSdfE6FwHgCRvbQrO9UxfOetl82x410DefbhhPmRBD4MkKg+HWvMfaRUP01sQDrA9jCZSNbA467v2WgorLNEad8oawJAvHVpyZeEtBaw3BvfeQu8a7ckikgyA=

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
